### ISSUE TITLE
Not seeing stuff appear at the MS server.

### ISSUE THREAD

**Issue by dpnova** [coinscrow/minerstat-linux#1]
![selection_021](https://user-images.githubusercontent.com/229943/27686614-e921e44a-5d16-11e7-9bca-f3a63ca51a5d.png)

Also my log seems to look different from your example ones on bitcointalk?

**Comment by dpnova** [comment]
More info:

```
Please, check your claymore-eth log file..
[Error: Error: Command failed: /bin/sh -c cd clients/claymore-eth; ./start.bash
Terminated
]
```

**Comment by dpnova** [comment]
I might have a crack at writing the linux client

**Comment by coinscrow** [comment]
Different because i made a screenshot with over ssh from mac.

you easily can debug. start the node the node will download the selected miner config file. after press ctrl + c to determinate the process.

open clients claymore-eth and check config.txt file with nano.
after start with ./start.batch if the miner run, there's a problem in the code.
if wont start there's an error at your config.

I invite you to slack to we can talk

**Comment by dpnova** [comment]
My screenshot was actually fine.. just takes a while for claymore to start the http interface. No problems there.

I'll close this for now. Cheers
